mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from pools import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pools/', include('pools.urls', namespace="pools", app_name="pools"))
]

pools/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name="home"),
	url(r'^question/(?P<question_id>\d+)/$', views.question, name="question"),
	url(r'^question/(?P<question_id>\d+)/results/$', views.results, name="results"),
	url(r'^question/(?P<question_id>\d+)/manage/$', views.manage, name="manage"),
	url(r'^question/(?P<question_id>\d+)/change_status/$', views.change_status, name="change_status"),
	url(r'^question/(?P<question_id>\d+)/vote/(?P<choice_id>\d+)/$', views.vote, name="vote"),
	url(r'^question/(?P<question_id>\d+)/add/(?P<choice_id>\d+)/$', views.add, name="add"),
	url(r'^question/(?P<question_id>\d+)/remove/(?P<choice_id>\d+)/$', views.remove, name="remove"),
]

pools/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.TextField()
	closed = models.BooleanField(default = False)
	pub_date = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question, null=True, related_name="choices")
	choice_text = models.CharField(max_length=255)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text + " " + str(self.votes) + " votes"

pools/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *

# Create your views here.
def index(request):
	questions = Question.objects.order_by('-pub_date')
	return render(request, 'index.html',{'questions':questions})

def question(request, question_id):
	question = Question.objects.get(id=question_id)
	choices = question.choices.all()
	return render(request,'question.html',{'question':question, 'choices': choices})

def results(request, question_id):
	question = Question.objects.get(id=question_id)
	choices = question.choices.all()
	totalVotes = 0;
	for ch in choices:
		totalVotes += ch.votes
	return render(request,'results.html',{'question':question, 'choices': choices,'totalVotes': totalVotes})

def vote(request, question_id,choice_id):
	choice = Choice.objects.get(id=choice_id)
	choice.votes += 1;
	choice.save()
	return redirect('pools:results',question_id=question_id)

def manage(request, question_id):
	question = Question.objects.get(id=question_id)
	choices = question.choices.all()
	all_choices = Choice.objects.filter(question=None)
	return render(request, 'manage.html',{'question':question, 'choices': choices,'all_choices': all_choices})

def add(request, question_id,choice_id):
	choice = Choice.objects.get(id=choice_id)
	question = Question.objects.get(id=question_id)
	choice.question = question
	choice.save()
	return redirect('pools:manage',question_id=question_id)

def remove(request, question_id,choice_id):
	choice = Choice.objects.get(id=choice_id)
	choice.votes = 0
	choice.question = None
	choice.save()
	return redirect('pools:manage',question_id=question_id)

def change_status(request, question_id):
	question = Question.objects.get(id=question_id)
	question.closed = not question.closed
	question.save()
	return redirect('pools:manage',question_id=question_id)

pools/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				{% block content %}{% endblock %}			
			</div>
		</div>
	</div>
	
</body>
</html>

pools/templates/index.html
{% extends 'base.html' %}

{% block title %}
	Pools
{% endblock %}

{% block content %}
	<h1>Bem-vindo a Pools</h1>

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Questões</div>

		<!-- Table -->
		<table class="table">
			
			<tbody>
			{% for question in questions %}
				<tr>
					<td><a href="{% url 'pools:question' question.id %}">{{ question.question_text }}</a></td>
				</tr>
			{% empty %}
				<tr>
					<td>Não há questões ainda.</td>
				</tr>
			{% endfor %}					
			</tbody>
		
		</table>
	</div>
	
{% endblock %}

pools/templates/manage.html
{% extends 'base.html' %}

{% block title %}
	Pools Manager
{% endblock %}

{% block content %}
	<h3>Questão: {{ question.question_text }}</h3>
	<p>
		Status: {% if question.closed %}
					Fechada
				{% else %}
					Aberta
				{% endif %}
		<a href="{% url 'pools:change_status' question_id=question.id %}" class="btn btn-primary btn-sm">
			{% if question.closed %}
				Abrir
			{% else %}
				Fechar
			{% endif %}
		</a>
	</p>
	<p>Data de criação: {{ question.pub_date }}</p>

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Escolhas</div>

		<!-- Table -->
		<table class="table">
			
			<tbody>
			{% for choice in choices %}
				<tr>
					<td>
						{{ choice.choice_text }} <a href="{% url 'pools:remove' question_id=question.id choice_id=choice.id %}" class="btn btn-danger btn-sm pull-right" onclick="return confirm('Voce tem certeza que deseja deletar escolha?')">Remover</a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td>Não há alternativas ainda.</td>
				</tr>
			{% endfor %}					
			</tbody>
		
		</table>
	</div>

	<hr>

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Todas as Escolhas</div>

		<!-- Table -->
		<table class="table">
			
			<tbody>
			{% for choice in all_choices %}
				<tr>
					<td>
						{{ choice.choice_text }} <a href="{% url 'pools:add' question_id=question.id choice_id=choice.id %}" class="btn btn-success btn-sm pull-right">Incluir</a>
					</td>
				</tr>
			{% empty %}
				<tr>
					<td>Não há alternativas ainda.</td>
				</tr>
			{% endfor %}					
			</tbody>
		
		</table>
	</div>

	<a class="btn btn-default" href="{% url 'pools:home' %}">Início</a>
	<a class="btn btn-default" href="{% url 'pools:question' question.id %}">Questão</a>
{% endblock %}

pools/templates/question.html
{% extends 'base.html' %}

{% block title %}
	Pool
{% endblock %}

{% block content %}
	<h3>Questão: {{ question.question_text }}</h3>
	<p>Fechada: {{ question.closed }}</p>
	<p>Data de criação: {{ question.pub_date }}</p>

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Escolhas</div>

		<!-- Table -->
		<table class="table">
			
			<tbody>
			{% for choice in choices %}
				<tr>
					<td>
						{{ choice.choice_text }} 
						{% if not question.closed %}
							<a class="btn btn-primary btn-sm" href="{% url 'pools:vote' question_id=question.id choice_id=choice.id %}">+ 1</a>
						{% endif %}
					</td>
				</tr>
			{% empty %}
				<tr>
					<td>Não há alternativas ainda.</td>
				</tr>
			{% endfor %}					
			</tbody>
		
		</table>
	</div>

	<a class="btn btn-default" href="{% url 'pools:home' %}">Início</a>
	<a class="btn btn-default" href="{% url 'pools:results' question.id %}">Resultados</a>
	<a class="btn btn-default" href="{% url 'pools:manage' question.id %}">Manage</a>
{% endblock %}

pools/templates/results.html
{% extends 'base.html' %}
{% load div_filter %}
{% block title %}
	Pool
{% endblock %}

{% block content %}
	<h3>Questão: {{ question.question_text }}</h3>
	<p>Fechada: {{ question.closed }}</p>
	<p>Data de criação: {{ question.pub_date }}</p>

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Escolhas</div>

		<!-- Table -->
		<table class="table">
			<thead>
				<tr>
					<th>Texto</th>
					<th>Votos</th>
					<th>Percentagem</th>
				</tr>
			</thead>
			
			<tbody>
			{% for choice in choices %}
				<tr>
					<td>{{ choice.choice_text }}</td>
					<td>{{ choice.votes }}</td>
					<td>
					{% if choice.votes != 0 %}
						{{ choice.votes|div:totalVotes }} %
					{% else %}
						0 %	
					{% endif %}
					</td>
				</tr>
			{% empty %}
				<tr>
					<td>Não há alternativas ainda.</td>
				</tr>
			{% endfor %}					
			</tbody>
		
		</table>
	</div>
	<a class="btn btn-default" href="{{request.META.HTTP_REFERER}}">Voltar</a>
	<a class="btn btn-default" href="{% url 'pools:home' %}">Início</a>
{% endblock %}